[ WARN:0] global ./modules/videoio/src/cap_v4l.cpp (890) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR] [1754260182.015795695] [target_detection_service]: Cannot open camera
[ERROR] [1754260712.839226027] [target_detection_service]: Node execution error: 
Failed to publish log message to rosout: publisher's context is invalid, at ./src/rcl/publisher.c:389
已连接到 192.168.31.89:5000
已连接到 192.168.31.89:5001
已连接到 192.168.31.89:5002
已连接到 192.168.31.89:5003
已连接到 192.168.31.89:5004
Traceback (most recent call last):
  File "/home/orangepi/ros2_workspace/NUEDC_H/automatic_aiming/install/automatic_aiming/lib/automatic_aiming/target_detect", line 33, in <module>
    sys.exit(load_entry_point('automatic-aiming', 'console_scripts', 'target_detect')())
  File "/home/orangepi/ros2_workspace/NUEDC_H/automatic_aiming/build/automatic_aiming/automatic_aiming/target_detect.py", line 563, in main
    rclpy.shutdown()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 130, in shutdown
    _shutdown(context=context)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/utilities.py", line 58, in shutdown
    return context.shutdown()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/context.py", line 102, in shutdown
    self.__context.shutdown()
rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:241
连接已断开
连接已断开
连接已断开
连接已断开
连接已断开
